import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
    en: {
        appName: "KaamConnect",
        tagline: "Apni Naukri, Apna Shehar",
        home: "Home",
        jobs: "Jobs",
        login: "Login",
        register: "Register",
        logout: "Logout",
        profile: "Profile",
        postJob: "Post a Job",
        myJobs: "My Jobs",
        myApplications: "My Applications",
        searchPlaceholder: "Search jobs or city...",
        heroTitle: "Find Work Near You",
        heroSubtitle: "Thousands of daily wage jobs in your city — driver, helper, cook, guard and more.",
        browseJobs: "Browse Jobs",
        postJobNow: "Post a Job",
        trustedBy: "Trusted by workers across small town India",
        applyWhatsApp: "Apply on WhatsApp",
        salary: "Salary",
        perDay: "per day",
        perMonth: "per month",
        location: "Location",
        category: "Category",
        jobType: "Job Type",
        fullTime: "Full Time",
        partTime: "Part Time",
        wfh: "Work From Home",
        fresher: "Fresher",
        trustScore: "Trust Score",
        reviews: "Reviews",
        noJobs: "No jobs found",
        loading: "Loading...",
        accepted: "Accepted",
        rejected: "Rejected",
        pending: "Pending",
        selectCity: "Select City",
        selectCategory: "Select Category",
        selectJobType: "Select Job Type",
        selectPayType: "Select Pay Type",
        daily: "Daily",
        monthly: "Monthly",
        submit: "Submit",
        cancel: "Cancel",
        save: "Save",
        edit: "Edit",
        delete: "Delete",
        back: "Back",
        next: "Next",
        name: "Full Name",
        phone: "Phone Number",
        password: "Password",
        city: "City",
        district: "District",
        role: "I am a",
        kaamgar: "Job Seeker",
        maalik: "Employer",
        bio: "About You",
        skills: "Skills",
        whatsapp: "WhatsApp Number",
        rateNow: "Rate Now",
        giveReview: "Write a Review",
        postedBy: "Posted by",
        applicants: "Applicants",
        dashboard: "Dashboard",
        voiceSearch: "Voice Search",
    },
    hi: {
        appName: "कामकनेक्ट",
        tagline: "अपनी नौकरी, अपना शहर",
        home: "होम",
        jobs: "नौकरियाँ",
        login: "लॉगिन",
        register: "रजिस्टर",
        logout: "लॉगआउट",
        profile: "प्रोफाइल",
        postJob: "नौकरी डालें",
        myJobs: "मेरी नौकरियाँ",
        myApplications: "मेरी अर्जियाँ",
        searchPlaceholder: "नौकरी या शहर खोजें...",
        heroTitle: "अपने शहर में काम ढूंढो",
        heroSubtitle: "आपके शहर में हजारों दैनिक मजदूरी की नौकरियाँ — ड्राइवर, हेल्पर, कुक, गार्ड और भी बहुत कुछ।",
        browseJobs: "नौकरियाँ देखें",
        postJobNow: "नौकरी डालें",
        trustedBy: "छोटे शहरों के मजदूरों का भरोसा",
        applyWhatsApp: "WhatsApp पर Apply करें",
        salary: "तनख्वाह",
        perDay: "प्रति दिन",
        perMonth: "प्रति महीना",
        location: "स्थान",
        category: "श्रेणी",
        jobType: "नौकरी का प्रकार",
        fullTime: "पूर्णकालिक",
        partTime: "अंशकालिक",
        wfh: "घर से काम",
        fresher: "फ्रेशर",
        trustScore: "ट्रस्ट स्कोर",
        reviews: "समीक्षाएँ",
        noJobs: "कोई नौकरी नहीं मिली",
        loading: "लोड हो रहा है...",
        accepted: "स्वीकृत",
        rejected: "अस्वीकृत",
        pending: "लंबित",
        selectCity: "शहर चुनें",
        selectCategory: "श्रेणी चुनें",
        selectJobType: "नौकरी का प्रकार चुनें",
        selectPayType: "भुगतान प्रकार चुनें",
        daily: "दैनिक",
        monthly: "मासिक",
        submit: "जमा करें",
        cancel: "रद्द करें",
        save: "सहेजें",
        edit: "संपादित करें",
        delete: "हटाएं",
        back: "वापस",
        next: "आगे",
        name: "पूरा नाम",
        phone: "फोन नंबर",
        password: "पासवर्ड",
        city: "शहर",
        district: "जिला",
        role: "मैं हूँ",
        kaamgar: "नौकरी खोजने वाला",
        maalik: "नियोक्ता",
        bio: "अपने बारे में",
        skills: "कौशल",
        whatsapp: "WhatsApp नंबर",
        rateNow: "रेटिंग दें",
        giveReview: "समीक्षा लिखें",
        postedBy: "द्वारा पोस्ट किया",
        applicants: "आवेदक",
        dashboard: "डैशबोर्ड",
        voiceSearch: "आवाज़ से खोजें",
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState("hi");
    const t = translations[lang];
    const toggleLang = () => setLang(prev => prev === "hi" ? "en" : "hi");

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLang = () => useContext(LanguageContext);